# Generated by Django 3.0.8 on 2020-07-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_basics_app', '0002_auto_20200719_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
